Update domain-list.json
nikolaischunk/discord-phishing-links pull request #461
Opened 2023-06-02 09:20 UTC by guyguy303

Added 2 new domain

2023-06-03 11:14 UTC, nikolaischunk requested changes

2023-06-03 11:14 UTC, nikolaischunk commented on domain-list.json
> +    "cutt.us",
`cutt.us` is a linkshortener. please don't add link shorteners, but add the complete scam redirect link so `cutt.us/XYZ`.

```suggestion
```

2023-06-03 12:15 UTC, guyguy303 commented on domain-list.json
> +    "cutt.us",
Ok i will remove it

2023-06-04 15:37 UTC, nikolaischunk approved these changes

2023-06-04 15:37 UTC, merged